
{{ title }}

## Computing ANCOVA and PairWise

```{r}
pdat = remove_group_data(dat[!is.na(dat[["{{ iv }}"]]),], "{{ dv.pos }}", "{{ iv }}")

res = residuals(lm({{ dv.pos }} ~ {{ dv.pre }} + {{ iv }}, data = pdat))
non.normal = getNonNormal(res, pdat$id, plimit = 0.05)

wdat = pdat[!pdat$id %in% non.normal,]

wdat.long <- rbind(wdat[,c("id","{{ iv }}")], wdat[,c("id","{{ iv }}")])
wdat.long[["{{ pivot.key }}"]] <- c(rep("pre", nrow(wdat)), rep("pos", nrow(wdat)))
wdat.long[["{{ pivot.key }}"]] <- factor(wdat.long[["{{ pivot.key }}"]], c("pre","pos"))
wdat.long[["{{ pivot.value }}"]] <- c(wdat[["{{ dv.pre }}"]], wdat[["{{ dv.pos }}"]])

ldat[["{{ iv }}"]] = wdat

(non.normal)
```

```{r}
aov = anova_test(wdat, {{ dv.pos }} ~ {{ dv.pre }} + {{ iv }})
laov[["{{ iv }}"]] <- get_anova_table(aov)
```

```{r, echo=FALSE, purl=FALSE}
kable(get_anova_table(aov), digits = 3)
```

```{r, echo=FALSE}
pwc <- emmeans_test(wdat, {{ dv.pos }} ~ {{ iv }}, covariate = {{ dv.pre }},
                    p.adjust.method = "bonferroni")
```

```{r, echo=FALSE, purl=FALSE}
kable(pwc, digits = 3)
```

```{r}
pwc.long <- emmeans_test(dplyr::group_by_at(wdat.long, "{{ iv }}"),
                         {{ pivot.value }} ~ {{ pivot.key }},
                         p.adjust.method = "bonferroni")
lpwc[["{{ iv }}"]] <- plyr::rbind.fill(pwc, pwc.long)
```

```{r, echo=FALSE, purl=FALSE}
kable(pwc.long, digits = 3)
```


```{r}
ds <- get.descriptives(wdat, "{{ dv.pos }}", "{{ iv }}", covar = "{{ dv.pre }}")
ds <- merge(ds[ds$variable != "{{ dv.pre }}",],
            ds[ds$variable == "{{ dv.pre }}", !colnames(ds) %in% c("variable")],
            by = "{{ iv }}", all.x = T, suffixes = c("", ".{{ dv.pre }}"))
ds <- merge(get_emmeans(pwc), ds, by = "{{ iv }}", suffixes = c(".emms", ""))
ds <- ds[,c("grupo","n","mean.{{ dv.pre }}","se.{{ dv.pre }}","mean","se","emmean","se.emms")]

colnames(ds) <- c("{{ iv }}", "N", paste0(c("M","SE")," (pre)"),
                  paste0(c("M","SE"), " (unadj)"), paste0(c("M", "SE"), " (adj)"))

lemms[["{{ iv }}"]] <- ds
```

```{r, echo=FALSE, purl=FALSE}
kable(ds, digits = 3)
```


### Plots for ancova

```{r}
plots <- oneWayAncovaPlots(
  wdat, "{{ dv.pos }}", "{{ iv }}", aov, list("{{ iv }}"=pwc), addParam = c("mean_se"),
  font.label.size=10, step.increase=0.05, p.label="p.adj",
  subtitle = which(aov$Effect == "{{ iv }}"))
```

```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
if (!is.null(nrow(plots[["{{ iv }}"]]$data)))
  plots[["{{ iv }}"]] + ggplot2::scale_color_manual(values = color[["{{ iv }}"]])
```


```{r}
plots <- oneWayAncovaBoxPlots(
  wdat, "{{ dv.pos }}", "{{ iv }}", aov, pwc, covar = "{{ dv.pre }}",
  theme = "classic", color = color[["{{ iv }}"]],
  subtitle = which(aov$Effect == "{{ iv }}"))
```

```{r, dpi=300, fig.width={{ fig.width.bar }}, fig.height={{ fig.height.bar }}}
if (length(unique(wdat[["{{ iv }}"]])) > 1)
  plots[["{{ iv }}"]] + ggplot2::ylab("{{ ylab }}") + ggplot2::scale_x_discrete(labels=c('pre', 'pos'))
```


```{r}
if (length(unique(wdat.long[["{{ iv }}"]])) > 1)
  plots <- oneWayAncovaBoxPlots(
    wdat.long, "{{ pivot.value }}", "{{ iv }}", aov, pwc.long, pre.post = "{{ pivot.key }}",
    theme = "classic", color = color$prepost)
```

```{r, dpi=300, fig.width={{ fig.width.pbar }}, fig.height={{ fig.height.pbar }}}
if (length(unique(wdat.long[["{{ iv }}"]])) > 1)
  plots[["{{ iv }}"]] + ggplot2::ylab("{{ ylab }}")
```


### Checking linearity assumption

```{r, dpi=300, fig.width=12, fig.height=8}
ggscatter(wdat, x = "{{ dv.pre }}", y = "{{ dv.pos }}", size = 0.5,
          color = "{{ iv }}", add = "reg.line")+
  stat_regline_equation(
    aes(label =  paste(..eq.label.., ..rr.label.., sep = "~~~~"), color = {{ iv }})
  )
```

### Checking normality and homogeneity

```{r}
res <- augment(lm({{ dv.pos }} ~ {{ dv.pre }} + {{ iv }}, data = wdat))
```

```{r}
shapiro_test(res$.resid)
```

```{r}
levene_test(res, .resid ~ {{ iv }})
```


## Computing ANOVA and PairWise (dif)

```{r}
pdat2 = pdat
pdat2[["{{ pivot.value }}"]] = pdat[["{{ dv.pos }}"]]-pdat[["{{ dv.pre }}"]]

res = residuals(lm({{ pivot.value }} ~ {{ iv }}, data = pdat2))
non.normal = getNonNormal(res, pdat2$id, plimit = 0.05)

wdat2 = pdat2[!pdat2$id %in% non.normal,]

#ldat[["{{ iv }}"]] = wdat2

(non.normal)
```

```{r}
aov = anova_test(wdat2, {{ pivot.value }} ~ {{ iv }})
#laov[["{{ iv }}"]] <- get_anova_table(aov)
```

```{r, echo=FALSE, purl=FALSE}
kable(get_anova_table(aov), digits = 3)
```

```{r, echo=FALSE}
pwc <- emmeans_test(wdat2, {{ pivot.value }} ~ {{ iv }},
                    p.adjust.method = "bonferroni")
```

```{r, echo=FALSE, purl=FALSE}
kable(pwc, digits = 3)
```


```{r}
ds <- get.descriptives(wdat2, "{{ pivot.value }}", "{{ iv }}", "common")
ds <- merge(get_emmeans(pwc), ds, by = "{{ iv }}", suffixes = c(".emms", ""))
ds <- ds[,c("{{ iv }}", "n", "mean", "se")]
colnames(ds) <- c("{{ iv }}", "N", "M", "SE")

lemms[["{{ iv }}"]] <- ds
```

```{r, echo=FALSE, purl=FALSE}
kable(ds, digits = 3)
```

### Plots for ancova

```{r}
plots <- oneWayAnovaPlots(
  wdat2, "{{ pivot.value }}", "{{ iv }}", aov, list("{{ pivot.value }}"=pwc), addParam = c("mean_se"),
  font.label.size=10, step.increase=0.05, p.label="p.adj",
  subtitle = which(aov$Effect == "{{ iv }}"))
```

```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
if (!is.null(nrow(plots[["{{ iv }}"]]$data)))
  plots[["{{ iv }}"]] + ggplot2::scale_color_manual(values = color[["{{ iv }}"]])
```

### Checking normality and homogeneity

```{r}
res <- augment(lm({{ pivot.value }} ~ {{ iv }}, data = wdat2))
```

```{r}
shapiro_test(res$.resid)
```

```{r}
levene_test(res, .resid ~ {{ iv }})
```
