

#{{ title }}

```{r, include=FALSE}
pdat = dat[!is.na(dat[["{{ iv1 }}"]]) & !is.na(dat[["{{ iv2 }}"]]),]
pdat = tryCatch(remove_group_data(pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}")), error = function(e) NULL)

if (!is.null(pdat) && length(unique(pdat[["{{ iv1 }}"]])) > 1 && length(unique(pdat[["{{ iv2 }}"]])) > 1) {
  pwc = anova.pwc(pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}"))
  if (!is.null(pwc[["{{ dv }}"]][["{{ iv1 }}"]]) || !is.null(pwc[["{{ dv }}"]][["{{ iv2 }}"]]))
    (apa <- get.anova.emmeans.with.ds(pwc, pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}"), "apa-format"))
}
```

```{r, echo=FALSE, purl=FALSE}
if (!is.null(pdat) && length(unique(pdat[["{{ iv1 }}"]])) > 1 && length(unique(pdat[["{{ iv2 }}"]])) > 1)
  kable(apa, digits = 3)
```

```{r, include=FALSE}
if (!is.null(pdat) && length(unique(pdat[["{{ iv1 }}"]])) > 1 && length(unique(pdat[["{{ iv2 }}"]])) > 1) {
  if (!is.null(pwc[["{{ dv }}"]][["{{ iv1 }}"]]) || !is.null(pwc[["{{ dv }}"]][["{{ iv2 }}"]])) {
    pdf <- get.anova.pwc.table(pwc, only.sig = F)
    (pdf <- pdf[!is.na(pdf$p.adj),])
  } else 
    pdf <- NULL
}
```

```{r, echo=FALSE, purl=FALSE}
if (!is.null(pdf) && !is.null(pdat) && length(unique(pdat[["{{ iv1 }}"]])) > 1 && length(unique(pdat[["{{ iv2 }}"]])) > 1) {
  pdf <- round.pval(pdf)
  kable(pdf[,c(".y.","{{ iv1 }}","{{ iv2 }}","group1","group2","estimate","conf.low",
               "conf.high","se","statistic","p","p.adj","p.adj.signif")], digits = 3)
}
```


```{r}
if (!is.null(pdat) && length(unique(pdat[["{{ iv1 }}"]])) > 1 && length(unique(pdat[["{{ iv2 }}"]])) > 1)
  if (!is.null(pwc[["{{ dv }}"]][["{{ iv1 }}"]]) || !is.null(pwc[["{{ dv }}"]][["{{ iv2 }}"]]))
    plots <- twoWayAnovaPlots(
      pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}"), aov2, pwc${{ dv }},
      addParam = c("mean_se"), font.label.size=10,
      step.increase=0.05, subtitle = which(aov2$Effect == "{{ iv1 }}:{{ iv2 }}"))
```

```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
if (!is.null(pdat) && !is.null(nrow(plots[["{{ iv1 }}"]]$data)))
  if (!is.null(pwc[["{{ dv }}"]][["{{ iv1 }}"]]) || !is.null(pwc[["{{ dv }}"]][["{{ iv2 }}"]]))
    plots[["{{ iv1 }}"]] + ggplot2::scale_color_manual(values = color[["{{ iv2 }}"]])
```

```{r, dpi=300, fig.width={{ fig.width }}, fig.height={{ fig.height }}}
if (!is.null(pdat) && !is.null(nrow(plots[["{{ iv2 }}"]]$data)))
  if (!is.null(pwc[["{{ dv }}"]][["{{ iv1 }}"]]) || !is.null(pwc[["{{ dv }}"]][["{{ iv2 }}"]]))
    plots[["{{ iv2 }}"]] + ggplot2::scale_color_manual(values = color[["{{ iv1 }}"]])
```


```{r}
#if (!is.null(pdat) && length(unique(pdat[["{{ iv1 }}"]])) > 1 && length(unique(pdat[["{{ iv2 }}"]])) > 1)
#  if (!is.null(pwc[["{{ dv }}"]][["{{ iv1 }}"]]) || !is.null(pwc[["{{ dv }}"]][["{{ iv2 }}"]]))
#    plots <- twoWayAncovaBoxPlots(
#      pdat, "{{ dv }}", c("{{ iv1 }}","{{ iv2 }}"), aov2, pwc${{ dv }},
#      theme = "classic", color = color[["{{ iv1 }}:{{ iv2 }}"]],
#      subtitle = which(aov2$Effect == "{{ iv1 }}:{{ iv2 }}"))
```

```{r, dpi=300, fig.width={{ fig.width.bar }}, fig.height={{ fig.height.bar }}}
#if (!is.null(pdat) && length(unique(pdat[["{{ iv1 }}"]])) > 1 && length(unique(pdat[["{{ iv2 }}"]])) > 1)
#  if (!is.null(pwc[["{{ dv }}"]][["{{ iv1 }}"]]) || !is.null(pwc[["{{ dv }}"]][["{{ iv2 }}"]]))
#    plots[["{{ iv1 }}:{{ iv2 }}"]] + ggplot2::ylab("{{ ylab }}") + ggplot2::scale_x_discrete(labels=c('pre', 'pos'))
```
